-- Insert default admin user
-- Password hash for 'suri@2005' using bcrypt (this would be generated by the auth system)
-- Note: In production, passwords should be hashed using bcrypt with proper salt

INSERT INTO users (email, password_hash, first_name, last_name, role, is_active) 
VALUES (
    'surindhar@gmail.com',
    '$2b$10$rQJ8vK9mF2xGzJ4nF8vK9eF2xGzJ4nF8vK9eF2xGzJ4nF8vK9eF2xG', -- This is a placeholder hash
    'Surindhar',
    'Admin',
    'admin',
    true
) ON CONFLICT (email) DO NOTHING;

-- Verify the admin user was created
SELECT id, email, first_name, last_name, role, is_active, created_at 
FROM users 
WHERE email = 'surindhar@gmail.com';
